export {
	type GateOutcome,
	STAGE_LABELS,
	applyGateDecision,
	canStartStage,
	createInitialProgress,
	getNextStage,
	getStageArtifacts,
	migratePaperProgress,
	pauseStage,
	registerArtifacts,
	requestGate,
	resetAwaitingGate,
	resumeStage,
	startStage,
} from "./stage-machine.ts";
export type { DeclaredArtifact } from "./stage-machine.ts";
export { buildResumeNudge, buildStagePrompt } from "./stage-prompts.ts";
export type { StagePromptContext } from "./stage-prompts.ts";
export {
	ARTIFACT_TYPES,
	PAPER_INBOX_VERSION,
	PAPER_PROGRESS_VERSION,
	type Artifact,
	type ArtifactCreator,
	type ArtifactRelation,
	type ArtifactRelationKind,
	type ArtifactRevision,
	type ArtifactType,
	type GateDecision,
	type GateDecisionKind,
	type GateRequest,
	type PaperProgress,
	type PaperInbox,
	type PaperProjectConfig,
	type QualityCheckItem,
	STAGE_IDS,
	type StageId,
	type StageProgress,
	type StageActivity,
	type StageActivityKind,
	type StageRun,
	type StageState,
	type StageStatus,
	type StageUsage,
	type InboxItem,
	type InboxItemKind,
	type InboxItemStatus,
	isArtifactType,
	isGateDecisionKind,
	isStageId,
} from "./types.ts";
